package com.spring.professional.exam.tutorial.module02.question04.service.a;

import com.spring.professional.exam.tutorial.module02.question04.ds.Employee;

public interface EmployeeRepository {
  Employee findEmployeeById(long id);

  void saveEmployee(Employee employee);

  void deleteEmployee(Employee employee);

  void findAndUpdateEmployeeById(long id, Employee employeeToMerge);
}

// deleteByEmail(String) is not part of the contract thus can't be  proxied by JDK or CGLIB
// method generated by the JDK is the only one that are present in the interface
// because of the JdkProxy implements this interface
